import requests
from bs4 import BeautifulSoup
import json
import re
import time
from datetime import datetime, timedelta

HEADERS = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36"}
CUTOFF = (datetime.utcnow() - timedelta(days=90)).strftime('%Y-%m-%d')

SFR_KW = ["single family","single-family","residential","subdivision","dwelling","detached",
    "density","lot","SFR","SF-","housing","home","acre","unit","R-1","R-2","R-3","PD","planned development"]

SIGNALS = ["rezone","rezoning","zone change","zoning change","zoning case","ZC-",
    "final plat","FP-","preliminary plat","PP-",
    "comprehensive plan","comp plan","future land use","land use plan"]

NOISE = ["agenda center tools","rss notify me","search agendas by","time period",
    "export export","export to excel","export to pdf","export to word",
    "click the subscriptions","notify me","subscribe","last week last month",
    "beautiful board","advisory committee","stakeholder","tax increment",
    "reinvestment zone","tirz","board of adjustment","zoning board of",
    "select the groups","would like to receive","powered by",
    "call to order","roll call","quorum","pledge of allegiance","invocation",
    "moment of silence","adjournment","adjourn","recess","reconvene",
    "approval of minutes","approve minutes","citizen comment","public comment",
    "visitor comment","staff report","city manager report","mayor report",
    "council report","proclamation","recognition","consent agenda",
    "regular agenda","new business","old business","unfinished business",
    "future agenda","agenda review","announcement","correspondence",
    "informational item","discussion only","no action","copyright",
    "privacy policy","all rights reserved","work session","workshop",
    "planning department community profile","development process development review",
    "building inspection health division","planning & development services",
    "cover memo","generated by gis","page 1 of","page 2 of","page 3 of"]

PDF_JUNK = [r'\d+\s+\d+\s+\d+\s*feet',r'[A-Z]:\\',r'P:\\',r'^\d[\d\s.,-]{20,}$',
    r'^source:',r'^\d+\s*$',r'^figure \d',r'legend',r'parcel id',r'coordinates']
PDF_JUNK_C = [re.compile(p, re.IGNORECASE) for p in PDF_JUNK]

PZ = ['planning','zoning','p&z','p & z','plan commission']
CC = ['city council','town council','council meeting','regular meeting','regular session']

DATE_P = [
    re.compile(r'((?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},?\s+20\d{2})', re.I),
    re.compile(r'((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2},?\s+20\d{2})', re.I),
    re.compile(r'(\d{1,2}/\d{1,2}/20\d{2})'),
    re.compile(r'(\d{1,2}-\d{1,2}-20\d{2})'),
    re.compile(r'(20\d{2}-\d{1,2}-\d{1,2})'),
    re.compile(r'(20\d{2}/\d{1,2}/\d{1,2})')]

VOTE_P = [
    re.compile(r'(approved|denied|tabled|continued|withdrawn|passed|failed)\s*(?:by a vote of\s*)?(\d+\s*[-to]+\s*\d+)?', re.I),
    re.compile(r'(unanimous(?:ly)?)\s*(approved|passed|denied)?', re.I),
    re.compile(r'motion\s+carried\s*(\d+\s*[-to]+\s*\d+)?', re.I)]

def pdate(raw):
    for f in ['%B %d %Y','%b %d %Y','%m/%d/%Y','%m-%d-%Y','%Y-%m-%d','%Y/%m/%d']:
        try: return datetime.strptime(raw.strip().replace(',',''),f).strftime('%Y-%m-%d')
        except: pass
    return ''

def fdate(text):
    for p in DATE_P:
        m = p.search(text)
        if m:
            d = pdate(m.group(1))
            if d and d >= CUTOFF: return d
    return ''

def fetch(url, t=25):
    try:
        r = requests.get(url, headers=HEADERS, timeout=t, allow_redirects=True)
        r.raise_for_status(); return r
    except: return None

def pdf_text(url):
    try:
        import pdfplumber, io
        r = requests.get(url, headers=HEADERS, timeout=45); r.raise_for_status()
        lines = []
        with pdfplumber.open(io.BytesIO(r.content)) as pdf:
            for pg in pdf.pages[:20]:
                t = pg.extract_text()
                if t:
                    for ln in t.split('\n'):
                        ln = ln.strip()
                        if len(ln) > 15: lines.append(ln)
        return lines
    except: return []

def is_pdf_junk(t):
    tl = t.lower()
    if len(t) < 25: return True
    if re.match(r'^[\d\s:/.,-]+$', tl): return True
    for p in PDF_JUNK_C:
        if p.search(tl): return True
    digits = sum(1 for c in t if c.isdigit())
    if len(t) > 0 and digits/len(t) > 0.5: return True
    return False

def is_noise(t):
    tl = t.lower()
    for p in NOISE:
        if p in tl: return True
    if re.match(r'^(www\.|http|tel:|fax:|email:|phone:)', tl): return True
    return False

def is_board_only(t):
    tl = t.lower()
    bw = ['committee','board','commission','subcommittee','task force']
    aw = ['amend','change','update','request','case','hearing','rezone','plat',
          'approve','consider','recommend','deny','acres','lots','district','from','to']
    return any(b in tl for b in bw) and not any(a in tl for a in aw)

def is_action(t):
    if is_board_only(t): return False
    tl = t.lower()
    return any(s.lower() in tl for s in SIGNALS)

def merge_lines(lines):
    merged = []; buf = ''
    for ln in lines:
        if is_pdf_junk(ln): continue
        if ln and ln[0].islower() and buf:
            buf += ' ' + ln
        elif re.match(r'^[\u2022\u2023\-\*]', ln) or re.match(r'^\d+\.', ln):
            if buf: merged.append(buf.strip())
            buf = re.sub(r'^[\u2022\u2023\-\*]\s*', '', ln)
            buf = re.sub(r'^\d+\.\s*', '', buf)
        else:
            if buf: merged.append(buf.strip())
            buf = ln
    if buf: merged.append(buf.strip())
    return merged

def filt(lines):
    merged = merge_lines(lines)
    out = []; seen = set()
    for ln in merged:
        ln = re.sub(r'\s+', ' ', ln).strip()
        if is_noise(ln) or is_pdf_junk(ln): continue
        if not is_action(ln): continue
        k = ln[:80].lower()
        if k in seen: continue
        seen.add(k); out.append(ln)
    return out

def get_votes(ml, items):
    d = {}
    for it in items:
        ws = [w for w in it.lower().split() if len(w)>4][:5]
        near = ' '.join(m for m in ml if any(w in m.lower() for w in ws[:3]))
        for vp in VOTE_P:
            vm = vp.search(near)
            if vm:
                pts = [g for g in vm.groups() if g]
                if pts: d[it] = ' '.join(pts).upper().strip(); break
    return d

def find_pdfs(soup, base):
    pdfs = []
    for a in soup.find_all('a', href=True):
        href = a['href']
        if not href.startswith('http'): href = requests.compat.urljoin(base, href)
        txt = a.get_text(strip=True)
        ctx = ''
        for p in a.parents:
            if p.name in ['tr','div','li','section','td','h2','h3','h4','span']:
                ctx = p.get_text(separator=' ', strip=True)[:400]; break
        is_ag = 'ViewFile/Agenda' in href or (href.lower().endswith('.pdf') and 'agenda' in (txt+ctx).lower())
        is_mn = 'ViewFile/Minutes' in href or (href.lower().endswith('.pdf') and 'minute' in (txt+ctx).lower())
        if not is_ag and not is_mn: continue
        dt = fdate(txt+' '+href+' '+ctx)
        full = (txt+' '+ctx).lower()
        bd = 'pz' if any(t in full for t in PZ) else ('cc' if any(t in full for t in CC) else 'unk')
        pdfs.append({'url':href,'date':dt,'board':bd,'type':'min' if is_mn else 'ag','ctx':full[:200]})
    return pdfs

# ============ CivicPlus Scraper ============

def scrape_cp(url, btype):
    res = {'url':'','date':'','items':[],'raw':0,'status':''}
    resp = fetch(url)
    if not resp: res['status']='could not reach site'; return res
    soup = BeautifulSoup(resp.text,'lxml')
    allp = find_pdfs(soup, url)
    for a in soup.find_all('a', href=True):
        h = a['href']
        if not h.startswith('http'): h = requests.compat.urljoin(url,h)
        if '/AgendaCenter/' in h and h != url and any(t in a.get_text(strip=True).lower() for t in (PZ if btype=='pz' else CC)):
            cr = fetch(h)
            if cr:
                allp.extend(find_pdfs(BeautifulSoup(cr.text,'lxml'), h))
                time.sleep(0.3)
    ags = [p for p in allp if p['type']=='ag' and (p['board']==btype or p['board']=='unk') and p['date']>=CUTOFF]
    if not ags: ags = [p for p in allp if p['type']=='ag' and p['date']>=CUTOFF]
    if not ags: res['status']='no recent agenda PDFs found'; return res
    ags.sort(key=lambda x:x['date'], reverse=True)
    for ag in ags[:3]:
        lines = pdf_text(ag['url'])
        if lines:
            items = filt(lines)
            if items:
                res['items']=items; res['date']=ag['date']; res['url']=ag['url']; res['raw']=len(lines)
                mns = [p for p in allp if p['type']=='min' and p['date']==ag['date']]
                if not mns: mns = [p for p in allp if p['type']=='min']
                for mn in mns[:1]:
                    ml = pdf_text(mn['url'])
                    if ml:
                        votes = get_votes(ml, items)
                        if votes: res['items'] = [i+' ['+votes[i]+']' if i in votes else i for i in items]
                    time.sleep(0.3)
                return res
            else:
                res['status'] = f'PDF parsed ({len(lines)} lines) but no rezone/plat/comp plan items'
                res['date']=ag['date']; res['url']=ag['url']; res['raw']=len(lines)
        time.sleep(0.5)
    if not res['status']: res['status']='PDFs found but could not extract text'
    return res

# ============ Municode Scraper ============

def scrape_municode(url, btype):
    res = {'url':url,'date':'','items':[],'raw':0,'status':''}
    resp = fetch(url)
    if not resp: res['status']='could not reach site'; return res
    soup = BeautifulSoup(resp.text,'lxml')
    links = []
    for a in soup.find_all('a', href=True):
        h = a['href']; t = a.get_text(strip=True)
        if not h.startswith('http'): h = requests.compat.urljoin(url,h)
        fl = (t+' '+h).lower()
        if 'meetings.municode' in fl or 'municode.com/meet' in fl or 'agenda' in fl:
            d = fdate(t+' '+h)
            links.append({'url':h,'date':d,'text':t,'pdf':h.lower().endswith('.pdf')})
    for a in soup.find_all('a', href=True):
        h = a['href']; t = a.get_text(strip=True)
        if not h.startswith('http'): h = requests.compat.urljoin(url,h)
        if h.lower().endswith('.pdf'):
            d = fdate(t+' '+h)
            if d: links.append({'url':h,'date':d,'text':t,'pdf':True})
    links.sort(key=lambda x:x['date'] if x['date'] else '', reverse=True)
    recent = [l for l in links if l['date']>=CUTOFF]
    for lnk in recent[:5]:
        if lnk['pdf']:
            lines = pdf_text(lnk['url'])
            if lines:
                items = filt(lines)
                if items:
                    res['items']=items; res['date']=lnk['date']; res['url']=lnk['url']; res['raw']=len(lines)
                    return res
        else:
            sub = fetch(lnk['url'])
            if sub:
                ss = BeautifulSoup(sub.text,'lxml')
                for a2 in ss.find_all('a', href=True):
                    h2 = a2['href']
                    if not h2.startswith('http'): h2 = requests.compat.urljoin(lnk['url'],h2)
                    if h2.lower().endswith('.pdf') or 'ViewFile' in h2:
                        lines = pdf_text(h2)
                        if lines:
                            items = filt(lines)
                            if items:
                                res['items']=items; res['date']=lnk['date']; res['url']=h2; res['raw']=len(lines)
                                return res
                        time.sleep(0.3)
                hi = []
                for el in ss.select('li, p, td, .agenda-item, [class*="agenda"], [class*="item"]'):
                    t = el.get_text(separator=' ', strip=True)
                    if 20 < len(t) < 800: hi.append(t)
                if hi:
                    items = filt(hi)
                    if items:
                        res['items']=items; res['date']=lnk['date']; res['url']=lnk['url']; res['raw']=len(hi)
                        return res
            time.sleep(0.5)
    if not res['status']: res['status']='no recent agenda items found'
    return res

# ============ Legistar Scraper ============

def scrape_legistar(url, btype):
    res = {'url':url,'date':'','items':[],'raw':0,'status':''}
    resp = fetch(url)
    if not resp: res['status']='could not reach site'; return res
    soup = BeautifulSoup(resp.text,'lxml')
    mtg_links = []
    for a in soup.find_all('a', href=True):
        h = a['href']; t = a.get_text(strip=True)
        if not h.startswith('http'): h = requests.compat.urljoin(url,h)
        fl = (t+' '+h).lower()
        bt = PZ if btype=='pz' else CC
        if any(b in fl for b in bt) and ('MeetingDetail' in h or 'meeting' in fl):
            d = fdate(t+' '+h)
            if d: mtg_links.append({'url':h,'date':d})
    if not mtg_links:
        for a in soup.find_all('a', href=True):
            h = a['href']; t = a.get_text(strip=True)
            if not h.startswith('http'): h = requests.compat.urljoin(url,h)
            if 'MeetingDetail' in h:
                d = fdate(t+' '+h)
                if d: mtg_links.append({'url':h,'date':d})
    mtg_links.sort(key=lambda x:x['date'], reverse=True)
    recent = [l for l in mtg_links if l['date']>=CUTOFF]
    for ml in recent[:3]:
        sub = fetch(ml['url'])
        if sub:
            ss = BeautifulSoup(sub.text,'lxml')
            for a2 in ss.find_all('a', href=True):
                h2 = a2['href']
                if not h2.startswith('http'): h2 = requests.compat.urljoin(ml['url'],h2)
                if h2.lower().endswith('.pdf'):
                    lines = pdf_text(h2)
                    if lines:
                        items = filt(lines)
                        if items:
                            res['items']=items; res['date']=ml['date']; res['url']=h2; res['raw']=len(lines)
                            return res
                    time.sleep(0.3)
            hi = []
            for el in ss.select('td, .LegiFileTitle, [class*="Title"]'):
                t = el.get_text(separator=' ', strip=True)
                if 20 < len(t) < 800: hi.append(t)
            if hi:
                items = filt(hi)
                if items:
                    res['items']=items; res['date']=ml['date']; res['url']=ml['url']; res['raw']=len(hi)
                    return res
        time.sleep(0.5)
    if not res['status']: res['status']='no recent matching meetings found'
    return res

# ============ Generic Scraper ============

def scrape_gen(url, btype):
    res = {'url':url,'date':'','items':[],'raw':0,'status':''}
    resp = fetch(url)
    if not resp: res['status']='could not reach site'; return res
    soup = BeautifulSoup(resp.text,'lxml')
    plinks = []
    for a in soup.find_all('a', href=True):
        h = a['href']; t = a.get_text(strip=True)
        if not h.startswith('http'): h = requests.compat.urljoin(url,h)
        fl = (t+' '+h).lower()
        if (h.lower().endswith('.pdf') or 'ViewFile' in h) and ('agenda' in fl or 'packet' in fl):
            d = fdate(t+' '+h)
            if d: plinks.append({'url':h,'date':d})
    plinks.sort(key=lambda x:x['date'], reverse=True)
    for pl in [p for p in plinks if p['date']>=CUTOFF][:3]:
        lines = pdf_text(pl['url'])
        if lines:
            items = filt(lines)
            if items:
                res['items']=items; res['date']=pl['date']; res['url']=pl['url']; res['raw']=len(lines)
                return res
        time.sleep(0.5)
    hlnks = []
    for a in soup.find_all('a', href=True):
        h = a['href']; t = a.get_text(strip=True)
        if not h.startswith('http'): h = requests.compat.urljoin(url,h)
        fl = (t+' '+h).lower()
        if ('agenda' in fl or 'meeting' in fl) and not h.lower().endswith('.pdf'):
            d = fdate(t+' '+h)
            if d: hlnks.append({'url':h,'date':d})
    hlnks.sort(key=lambda x:x['date'], reverse=True)
    for hl in [h for h in hlnks if h['date']>=CUTOFF][:3]:
        sub = fetch(hl['url'])
        if sub:
            ss = BeautifulSoup(sub.text,'lxml')
            for a2 in ss.find_all('a', href=True):
                h2 = a2['href']
                if not h2.startswith('http'): h2 = requests.compat.urljoin(hl['url'],h2)
                if h2.lower().endswith('.pdf') or 'ViewFile' in h2:
                    lines = pdf_text(h2)
                    if lines:
                        items = filt(lines)
                        if items:
                            res['items']=items; res['date']=hl['date']; res['url']=h2; res['raw']=len(lines)
                            return res
                    time.sleep(0.3)
            hi = []
            for el in ss.select('li, p, td, .agenda-item'):
                t2 = el.get_text(separator=' ', strip=True)
                if 20 < len(t2) < 800: hi.append(t2)
            if hi:
                items = filt(hi)
                if items:
                    res['items']=items; res['date']=hl['date']; res['url']=hl['url']; res['raw']=len(hi)
                    return res
        time.sleep(0.5)
    if not res['status']: res['status']='no matching items found'
    return res

# ============ Router ============

def scrape_board(url, city, bname):
    bt = 'pz' if 'Zoning' in bname else 'cc'
    r = {'board':bname,'agenda_url':url,'meeting_date':'','items':[],'sfr_items':[],'status':'success'}
    try:
        if '/AgendaCenter' in url:
            d = scrape_cp(url, bt)
        elif 'legistar.com' in url:
            d = scrape_legistar(url, bt)
        elif 'municode' in url.lower() or any(x in url.lower() for x in ['pondertx.com','cityofheartland']):
            d = scrape_municode(url, bt)
        else:
            d = scrape_gen(url, bt)
        r['items']=d['items']; r['meeting_date']=d.get('date',''); r['agenda_url']=d.get('url',url)
        if d.get('status') and not d['items']: r['status']=d['status']
        for it in r['items']:
            kw = [k for k in SFR_KW if k.lower() in it.lower()]
            if kw: r['sfr_items'].append(it+' [Keywords: '+', '.join(kw[:5])+']')
    except Exception as e:
        r['status']='error: '+str(e)[:120]
    return r

MUNIS = [
    {"n":"Arlington","co":"Tarrant","pz":"https://www.arlingtontx.gov/city_hall/boards_and_commissions/planning_and_zoning_commission","cc":"https://www.arlingtontx.gov/city_hall/government/city_council/city_council_meetings"},
    {"n":"Fort Worth","co":"Tarrant","pz":"https://fortworthtexas.legistar.com/Calendar.aspx","cc":"https://fortworthtexas.legistar.com/Calendar.aspx"},
    {"n":"Mansfield","co":"Tarrant","pz":"https://www.mansfieldtexas.gov/925/Planning-Zoning-Commission","cc":"https://www.mansfieldtexas.gov/AgendaCenter"},
    {"n":"Keller","co":"Tarrant","pz":"https://www.cityofkeller.com/services/development-services/planning-zoning","cc":"https://www.cityofkeller.com/government/city-council/agendas-minutes"},
    {"n":"Southlake","co":"Tarrant","pz":"https://www.cityofsouthlake.com/AgendaCenter","cc":"https://www.cityofsouthlake.com/AgendaCenter"},
    {"n":"Colleyville","co":"Tarrant","pz":"https://www.colleyville.com/government/boards-commissions/planning-zoning-commission","cc":"https://www.colleyville.com/government/city-council/agendas-minutes"},
    {"n":"Grapevine","co":"Tarrant","pz":"https://www.grapevinetexas.gov/AgendaCenter","cc":"https://www.grapevinetexas.gov/AgendaCenter"},
    {"n":"Bedford","co":"Tarrant","pz":"https://www.bedfordtx.gov/AgendaCenter","cc":"https://www.bedfordtx.gov/AgendaCenter"},
    {"n":"Euless","co":"Tarrant","pz":"https://www.eulesstx.gov/city-government/boards-commissions/planning-zoning-commission","cc":"https://www.eulesstx.gov/city-government/city-council/agendas-minutes"},
    {"n":"Hurst","co":"Tarrant","pz":"https://www.hursttx.gov/government/boards-commissions/planning-zoning-commission","cc":"https://www.hursttx.gov/government/city-council/agendas-minutes"},
    {"n":"North Richland Hills","co":"Tarrant","pz":"https://www.nrhtx.com/AgendaCenter","cc":"https://www.nrhtx.com/AgendaCenter"},
    {"n":"Burleson","co":"Tarrant","pz":"https://www.burlesontx.com/AgendaCenter","cc":"https://www.burlesontx.com/AgendaCenter"},
    {"n":"Saginaw","co":"Tarrant","pz":"https://www.ci.saginaw.tx.us/AgendaCenter","cc":"https://www.ci.saginaw.tx.us/AgendaCenter"},
    {"n":"Benbrook","co":"Tarrant","pz":"https://www.benbrook-tx.gov/AgendaCenter","cc":"https://www.benbrook-tx.gov/AgendaCenter"},
    {"n":"Crowley","co":"Tarrant","pz":"https://www.ci.crowley.tx.us/AgendaCenter","cc":"https://www.ci.crowley.tx.us/AgendaCenter"},
    {"n":"Watauga","co":"Tarrant","pz":"https://www.cowtx.gov/AgendaCenter","cc":"https://www.cowtx.gov/AgendaCenter"},
    {"n":"Kennedale","co":"Tarrant","pz":"https://www.kennedale.com/AgendaCenter","cc":"https://www.kennedale.com/AgendaCenter"},
    {"n":"Azle","co":"Tarrant","pz":"https://www.cityofazle.com/AgendaCenter","cc":"https://www.cityofazle.com/AgendaCenter"},
    {"n":"Haslet","co":"Tarrant","pz":"https://www.haslet.org/AgendaCenter","cc":"https://www.haslet.org/AgendaCenter"},
    {"n":"Trophy Club","co":"Tarrant","pz":"https://www.trophyclub.org/AgendaCenter","cc":"https://www.trophyclub.org/AgendaCenter"},
    {"n":"Haltom City","co":"Tarrant","pz":"https://www.haltomcitytx.com/AgendaCenter","cc":"https://www.haltomcitytx.com/AgendaCenter"},
    {"n":"White Settlement","co":"Tarrant","pz":"https://www.wstx.us/AgendaCenter","cc":"https://www.wstx.us/AgendaCenter"},
    {"n":"Forest Hill","co":"Tarrant","pz":"https://www.foresthilltx.org/AgendaCenter","cc":"https://www.foresthilltx.org/AgendaCenter"},
    {"n":"Coppell","co":"Tarrant","pz":"https://www.coppelltx.gov/AgendaCenter","cc":"https://www.coppelltx.gov/AgendaCenter"},
    {"n":"Dallas","co":"Dallas","pz":"https://dallascityhall.com/government/cityplan/Pages/default.aspx","cc":"https://dallascityhall.com/government/citycouncil/Pages/city-council-agendas.aspx"},
    {"n":"Irving","co":"Dallas","pz":"https://www.cityofirving.org/AgendaCenter","cc":"https://www.cityofirving.org/AgendaCenter"},
    {"n":"Grand Prairie","co":"Dallas","pz":"https://www.gptx.org/AgendaCenter","cc":"https://www.gptx.org/AgendaCenter"},
    {"n":"Garland","co":"Dallas","pz":"https://www.garlandtx.gov/AgendaCenter","cc":"https://www.garlandtx.gov/AgendaCenter"},
    {"n":"Mesquite","co":"Dallas","pz":"https://www.cityofmesquite.com/AgendaCenter","cc":"https://www.cityofmesquite.com/AgendaCenter"},
    {"n":"Richardson","co":"Dallas","pz":"https://www.cor.net/government/boards-and-commissions/plan-commission","cc":"https://www.cor.net/government/city-council/agendas-and-minutes"},
    {"n":"Carrollton","co":"Dallas","pz":"https://www.cityofcarrollton.com/government/boards-commissions/planning-zoning-commission","cc":"https://www.cityofcarrollton.com/government/city-council/agendas-minutes"},
    {"n":"Farmers Branch","co":"Dallas","pz":"https://www.farmersbranchtx.gov/AgendaCenter","cc":"https://www.farmersbranchtx.gov/AgendaCenter"},
    {"n":"DeSoto","co":"Dallas","pz":"https://www.ci.desoto.tx.us/AgendaCenter","cc":"https://www.ci.desoto.tx.us/AgendaCenter"},
    {"n":"Cedar Hill","co":"Dallas","pz":"https://www.cedarhilltx.com/AgendaCenter","cc":"https://www.cedarhilltx.com/AgendaCenter"},
    {"n":"Lancaster","co":"Dallas","pz":"https://www.lancaster-tx.com/AgendaCenter","cc":"https://www.lancaster-tx.com/AgendaCenter"},
    {"n":"Duncanville","co":"Dallas","pz":"https://www.duncanville.com/AgendaCenter","cc":"https://www.duncanville.com/AgendaCenter"},
    {"n":"Rowlett","co":"Dallas","pz":"https://www.ci.rowlett.tx.us/AgendaCenter","cc":"https://www.ci.rowlett.tx.us/AgendaCenter"},
    {"n":"Seagoville","co":"Dallas","pz":"https://www.seagoville.us/AgendaCenter","cc":"https://www.seagoville.us/AgendaCenter"},
    {"n":"Balch Springs","co":"Dallas","pz":"https://www.cityofbalchsprings.com/AgendaCenter","cc":"https://www.cityofbalchsprings.com/AgendaCenter"},
    {"n":"Addison","co":"Dallas","pz":"https://www.addisontexas.net/AgendaCenter","cc":"https://www.addisontexas.net/AgendaCenter"},
    {"n":"Glenn Heights","co":"Dallas","pz":"https://www.glennheightstx.com/AgendaCenter","cc":"https://www.glennheightstx.com/AgendaCenter"},
    {"n":"Plano","co":"Collin","pz":"https://www.plano.gov/AgendaCenter","cc":"https://www.plano.gov/AgendaCenter"},
    {"n":"McKinney","co":"Collin","pz":"https://www.mckinneytexas.org/AgendaCenter","cc":"https://www.mckinneytexas.org/AgendaCenter"},
    {"n":"Frisco","co":"Collin","pz":"https://www.friscotexas.gov/AgendaCenter","cc":"https://www.friscotexas.gov/AgendaCenter"},
    {"n":"Allen","co":"Collin","pz":"https://www.cityofallen.org/AgendaCenter","cc":"https://www.cityofallen.org/AgendaCenter"},
    {"n":"Wylie","co":"Collin","pz":"https://www.wylietexas.gov/AgendaCenter","cc":"https://www.wylietexas.gov/AgendaCenter"},
    {"n":"Anna","co":"Collin","pz":"https://www.annatexas.gov/AgendaCenter","cc":"https://www.annatexas.gov/AgendaCenter"},
    {"n":"Celina","co":"Collin","pz":"https://www.celina-tx.gov/AgendaCenter","cc":"https://www.celina-tx.gov/AgendaCenter"},
    {"n":"Prosper","co":"Collin","pz":"https://www.prospertx.gov/AgendaCenter","cc":"https://www.prospertx.gov/AgendaCenter"},
    {"n":"Princeton","co":"Collin","pz":"https://www.princetontx.gov/AgendaCenter","cc":"https://www.princetontx.gov/AgendaCenter"},
    {"n":"Melissa","co":"Collin","pz":"https://www.melissatx.gov/AgendaCenter","cc":"https://www.melissatx.gov/AgendaCenter"},
    {"n":"Sachse","co":"Collin","pz":"https://www.cityofsachse.com/AgendaCenter","cc":"https://www.cityofsachse.com/AgendaCenter"},
    {"n":"Lucas","co":"Collin","pz":"https://www.lucastexas.us/AgendaCenter","cc":"https://www.lucastexas.us/AgendaCenter"},
    {"n":"Farmersville","co":"Collin","pz":"https://www.farmersvilletx.com/AgendaCenter","cc":"https://www.farmersvilletx.com/AgendaCenter"},
    {"n":"Fairview","co":"Collin","pz":"https://www.fairviewtexas.org/AgendaCenter","cc":"https://www.fairviewtexas.org/AgendaCenter"},
    {"n":"Murphy","co":"Collin","pz":"https://www.murphytx.org/AgendaCenter","cc":"https://www.murphytx.org/AgendaCenter"},
    {"n":"Lavon","co":"Collin","pz":"https://www.cityoflavon.com/AgendaCenter","cc":"https://www.cityoflavon.com/AgendaCenter"},
    {"n":"Van Alstyne","co":"Collin","pz":"https://www.vanalstyne.org/AgendaCenter","cc":"https://www.vanalstyne.org/AgendaCenter"},
    {"n":"Parker","co":"Collin","pz":"https://www.parkertexas.us/AgendaCenter","cc":"https://www.parkertexas.us/AgendaCenter"},
    {"n":"Denton","co":"Denton","pz":"https://www.cityofdenton.com/AgendaCenter","cc":"https://www.cityofdenton.com/AgendaCenter"},
    {"n":"Lewisville","co":"Denton","pz":"https://www.cityoflewisville.com/government/boards-commissions/planning-zoning-commission","cc":"https://www.cityoflewisville.com/government/city-council/agendas-minutes"},
    {"n":"Flower Mound","co":"Denton","pz":"https://www.flower-mound.com/AgendaCenter","cc":"https://www.flower-mound.com/AgendaCenter"},
    {"n":"Little Elm","co":"Denton","pz":"https://www.littleelm.org/AgendaCenter","cc":"https://www.littleelm.org/AgendaCenter"},
    {"n":"Corinth","co":"Denton","pz":"https://www.cityofcorinth.com/AgendaCenter","cc":"https://www.cityofcorinth.com/AgendaCenter"},
    {"n":"The Colony","co":"Denton","pz":"https://www.thecolonytx.gov/AgendaCenter","cc":"https://www.thecolonytx.gov/AgendaCenter"},
    {"n":"Argyle","co":"Denton","pz":"https://www.argyletx.com/AgendaCenter","cc":"https://www.argyletx.com/AgendaCenter"},
    {"n":"Aubrey","co":"Denton","pz":"https://www.aubreytx.gov/AgendaCenter","cc":"https://www.aubreytx.gov/AgendaCenter"},
    {"n":"Sanger","co":"Denton","pz":"https://www.sangertexas.org/AgendaCenter","cc":"https://www.sangertexas.org/AgendaCenter"},
    {"n":"Pilot Point","co":"Denton","pz":"https://www.cityofpilotpoint.org/AgendaCenter","cc":"https://www.cityofpilotpoint.org/AgendaCenter"},
    {"n":"Northlake","co":"Denton","pz":"https://www.northlaketx.org/AgendaCenter","cc":"https://www.northlaketx.org/AgendaCenter"},
    {"n":"Justin","co":"Denton","pz":"https://www.cityofjustin.com/AgendaCenter","cc":"https://www.cityofjustin.com/AgendaCenter"},
    {"n":"Roanoke","co":"Denton","pz":"https://www.roanoketexas.com/AgendaCenter","cc":"https://www.roanoketexas.com/AgendaCenter"},
    {"n":"Cross Roads","co":"Denton","pz":"https://www.crossroadstx.gov/AgendaCenter","cc":"https://www.crossroadstx.gov/AgendaCenter"},
    {"n":"Oak Point","co":"Denton","pz":"https://www.oakpointtexas.com/AgendaCenter","cc":"https://www.oakpointtexas.com/AgendaCenter"},
    {"n":"Ponder","co":"Denton","pz":"https://www.pondertx.com/bc-pz","cc":"https://www.pondertx.com/town-council"},
    {"n":"Highland Village","co":"Denton","pz":"https://www.highlandvillage.org/AgendaCenter","cc":"https://www.highlandvillage.org/AgendaCenter"},
    {"n":"Waxahachie","co":"Ellis","pz":"https://www.waxahachie.com/AgendaCenter","cc":"https://www.waxahachie.com/AgendaCenter"},
    {"n":"Midlothian","co":"Ellis","pz":"https://www.midlothian.tx.us/AgendaCenter","cc":"https://www.midlothian.tx.us/AgendaCenter"},
    {"n":"Ennis","co":"Ellis","pz":"https://www.ennis-texas.com/AgendaCenter","cc":"https://www.ennis-texas.com/AgendaCenter"},
    {"n":"Red Oak","co":"Ellis","pz":"https://www.redoaktx.org/AgendaCenter","cc":"https://www.redoaktx.org/AgendaCenter"},
    {"n":"Rockwall","co":"Rockwall","pz":"https://www.rockwall.com/AgendaCenter","cc":"https://www.rockwall.com/AgendaCenter"},
    {"n":"Heath","co":"Rockwall","pz":"https://www.heathtx.com/AgendaCenter","cc":"https://www.heathtx.com/AgendaCenter"},
    {"n":"Fate","co":"Rockwall","pz":"https://www.fatetx.gov/AgendaCenter","cc":"https://www.fatetx.gov/AgendaCenter"},
    {"n":"Royse City","co":"Rockwall","pz":"https://www.roysecity.com/AgendaCenter","cc":"https://www.roysecity.com/AgendaCenter"},
    {"n":"Forney","co":"Kaufman","pz":"https://www.forneytx.gov/AgendaCenter","cc":"https://www.forneytx.gov/AgendaCenter"},
    {"n":"Terrell","co":"Kaufman","pz":"https://www.cityofterrell.com/AgendaCenter","cc":"https://www.cityofterrell.com/AgendaCenter"},
    {"n":"Crandall","co":"Kaufman","pz":"https://www.cityofcrandall.com/AgendaCenter","cc":"https://www.cityofcrandall.com/AgendaCenter"},
    {"n":"Kaufman","co":"Kaufman","pz":"https://www.kaufmantx.org/AgendaCenter","cc":"https://www.kaufmantx.org/AgendaCenter"},
    {"n":"Heartland","co":"Kaufman","pz":"https://www.cityofheartland.com/AgendaCenter","cc":"https://www.cityofheartland.com/AgendaCenter"},
    {"n":"Cleburne","co":"Johnson","pz":"https://www.cleburne.net/AgendaCenter","cc":"https://www.cleburne.net/AgendaCenter"},
    {"n":"Joshua","co":"Johnson","pz":"https://www.cityofjoshua.us/AgendaCenter","cc":"https://www.cityofjoshua.us/AgendaCenter"},
    {"n":"Alvarado","co":"Johnson","pz":"https://www.alvaradotx.gov/AgendaCenter","cc":"https://www.alvaradotx.gov/AgendaCenter"},
    {"n":"Weatherford","co":"Parker","pz":"https://www.weatherfordtx.gov/AgendaCenter","cc":"https://www.weatherfordtx.gov/AgendaCenter"},
    {"n":"Hudson Oaks","co":"Parker","pz":"https://www.hudsonoaks.com/AgendaCenter","cc":"https://www.hudsonoaks.com/AgendaCenter"},
    {"n":"Willow Park","co":"Parker","pz":"https://www.willowpark.org/AgendaCenter","cc":"https://www.willowpark.org/AgendaCenter"},
    {"n":"Aledo","co":"Parker","pz":"https://www.aledotx.gov/AgendaCenter","cc":"https://www.aledotx.gov/AgendaCenter"},
    {"n":"Decatur","co":"Wise","pz":"https://www.decaturtx.org/AgendaCenter","cc":"https://www.decaturtx.org/AgendaCenter"},
    {"n":"Bridgeport","co":"Wise","pz":"https://www.cityofbridgeport.net/AgendaCenter","cc":"https://www.cityofbridgeport.net/AgendaCenter"}
]

def scrape_city(m):
    data = {'name':m['n'],'county':m['co'],'boards':[]}
    same_url = m['pz'] == m['cc']
    seen_items = set()
    for key, bname in [('pz','Planning & Zoning'),('cc','City Council')]:
        url = m[key]
        print(f"    {bname}...", end=' ', flush=True)
        r = scrape_board(url, m['n'], bname)
        if same_url and key == 'cc':
            r['items'] = [i for i in r['items'] if i[:80].lower() not in seen_items]
            r['sfr_items'] = [i for i in r['sfr_items'] if i.split(' [Keywords')[0][:80].lower() not in seen_items]
            if not r['items']: r['status'] = 'same agenda center - items shown under P&Z'
        if key == 'pz':
            seen_items = {i[:80].lower() for i in r['items']}
        print(f"{len(r['items'])} items | {r['status']}")
        data['boards'].append(r)
        time.sleep(1)
    return data

def main():
    print(f"DFW Agenda Scraper v8 (Deep PDF | 90-Day | Multi-Platform)")
    print(f"Cutoff: {CUTOFF}")
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"Scanning {len(MUNIS)} cities...\n")
    sums = []; ti=0; ts=0
    for i,m in enumerate(MUNIS):
        print(f"[{i+1}/{len(MUNIS)}] {m['n']} ({m['co']} Co.)")
        cd = scrape_city(m)
        for b in cd['boards']:
            ti+=len(b['items']); ts+=len(b['sfr_items'])
            sums.append({'county':cd['county'],'city':cd['name'],'board':b['board'],
                'meeting_date':b.get('meeting_date',''),'agenda_url':b.get('agenda_url',''),
                'items':b['items'],'sfr_items':b['sfr_items'],'status':b.get('status','success')})
    out = {'metadata':{'last_updated':datetime.utcnow().isoformat()+'Z',
        'cities_scanned':len(MUNIS),'cutoff_date':CUTOFF,
        'total_action_items':ti,'total_sfr_items':ts},'summaries':sums}
    with open('agenda_data.json','w',encoding='utf-8') as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(f"\nDone! Actions: {ti} | SFR: {ts}")

if __name__ == '__main__':
    main()
